### ISSUE TITLE
Firefox keyboard shortcut support

### ISSUE THREAD

**Issue by t1merickson** [austintraver/merge#1]
Thank you for making this Austin! 

If possible, could you please add support in the firefox extension to activate the extension by keyboard shortcut? I believe Chrome gives this functionality for free, but you need to build it into the extension for firefox. 

Here is the applicable documentation: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands

Should only take a few minutes to add. Cheers!

**Comment by austintraver** [comment]
I think this is a great enhancement to add, and definitely one that will be simple to implement. I believe it will take me longer than a few minutes to add it, but given what a small feature it is, and how much value it can produce, I will add this to the roadmap for the next update for Merge.

**Comment by austintraver** [comment]
Ok, not necessarily a few seconds, but it was a fun challenge to see how fast I could build this. This evening I will publish the updated version. @t1merickson Feel free to look over the change, which was made in commit ab4fc22
